version: "3.9"

services:
  app:
    build: .
    container_name: node-docker-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
